# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  # 1) check every push regardless of branch
  push:
  # 2) every 4th day of month at CET noon last commit on default branch (i.e. master)
  schedule:
    - cron:  "0 11 4 * *"

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-20.04, r: 'devel'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Store API key unix-alike
        if: runner.os != 'Windows'
        run: |
          echo GOOGLE_API_KEY="$GOOGLE_API_KEY" >> ~/.Renviron
        shell: bash

      - name: Store API key windows
        if: runner.os == 'Windows'
        run: |
          Add-Content c:\Users\$env:USERNAME\Documents\.Renviron "GOOGLE_API_KEY='"+ $GOOGLE_API_KEY + "'" -Encoding utf-8
        shell: pwsh

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: rcmdcheck

      - uses: r-lib/actions/check-r-package@v1
