# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  # 1) check every push regardless of branch
  push:
  # 2) every 4th day of month at CET noon last commit on default branch (i.e. master)
  schedule:
    - cron:  "0 11 4 * *"
  # 3) manually if need be...
  workflow_dispatch:

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-22.04, r: 'devel'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Store API key unix-alike
        if: runner.os != 'Windows'
        run: |
          echo GOOGLE_API_KEY="$GOOGLE_API_KEY" >> ~/.Renviron
        shell: bash

      - name: Store API key windows
        if: runner.os == 'Windows'
        run: |
          echo GOOGLE_API_KEY="$GOOGLE_API_KEY" >> .Renviron
        shell: bash

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'

      - name: Test coverage
        if: runner.os == 'Linux'
        run: covr::codecov()
        shell: Rscript {0}
